### ISSUE TITLE
Make restore script ignore binary files

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/vagrant-geonode#23]

**Comment by brucecrevensten** [comment]
Alternatively, make it only find files of type XML... is that valid for the only filetype that contains strings needing to be swapped?

**Comment by cstephen** [comment]
We need to make sure to include the SQL dump, too. Grep'ing through the files on a fresh restore from geonode-test, I see:

``` bash
$ grep -Rl geonode-test *
data/logs/geoserver.log.1
data/logs/geoserver.log.2
data/logs/geoserver.log
data/demo/WMS_GetLegendGraphic-SLD.url
data/demo/WFS_transactionInsert.xml
data/security/auth/geonodeAuthProvider/config.xml
geonode-backup.sql
```

Also, uploaded Shapefiles are given hard-coded file system paths that need replaced:

``` bash
$ grep -Rl 'file:/'
magnitude_3/datastore.xml
cop_miz/datastore.xml
```

So according to our experience thus far, this should cover it:
- .sql file
- .xml files
- .url files

But who knows if there are other types of files we haven't seen yet that will need string replacement treatment?

**Comment by brucecrevensten** [comment]
It seems more hazardous to try and whitelist binaries than to whitelist text files... and it wasn't clear to me if `find` has a syntax that would really work for us here?  I'll give this a shot when preparing my DB today, just to give it a whirl and you can test out the restore.  Agreed there is some risk.
