### ISSUE TITLE
Create recipe used during ingest to improve display of NCEP data

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/vagrant-geonode#27]
Goal is to produce a GDAL recipe that does these things:
- remove "beam of light" on antemeridian
- crop source data to optimal extent (3572?)
- project to 3572

**Comment by EarthScientist** [comment]
I have found a proper FTP site that stores all of the Reanalysis data for the surface fields.  I have also found that the reproject on the fly calculation that is being performed by the GeoServer is not being performed correctly for some reason.  I have found a way to reproject this using a combination of gdalwarp and gdal_translate.  It isnt exactly a recipe yet, but it is close.

Surface fields:  ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis/surface/

**Comment by EarthScientist** [comment]
this recipe is complete and currently working.  closing.
