### ISSUE TITLE
Move preprocessing scripts or otherwise handle issue

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/vagrant-geonode#38]
...the issue is that the `geonode/portal/.gitignore` file ignores `NCEP/*` which is a bit confusing if you're adding files there.

But we don't necessarily think these "adaptor" scripts all belong in the same bucket as the Vagrant stuff.

?

**Comment by BobTorgerson** [comment]
The .gitignore file was setup that way because the script was dumping the final GeoTiffs into that same NCEP directory, and I didn't want them to clutter up the git status. I do agree that keeping these scripts permanently tied to the vagrant-geonode repository doesn't make sense though, so we could likely come up with a better repo for them to live in.

**Comment by brucecrevensten** [comment]
What do you think about moving them into the snap-arctic-portal repo under
a directory, `scripts` ?

On Wed, Dec 2, 2015 at 9:30 AM, BobTorgerson notifications@github.com
wrote:

> The .gitignore file was setup that way because the script was dumping the
> final GeoTiffs into that same NCEP directory, and I didn't want them to
> clutter up the git status. I do agree that keeping these scripts
> permanently tied to the vagrant-geonode repository doesn't make sense
> though, so we could likely come up with a better repo for them to live in.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ua-snap/vagrant-geonode/issues/38#issuecomment-161390916
> .

## 

_Bruce Crevensten_

_Senior Software Engineer_
(SNAP) Scenarios Network for Alaska & Arctic Planning
www.snap.uaf.edu

**Comment by BobTorgerson** [comment]
That seems like a logical place to put them to me. We could use that repository to hold all of our "data recipes" for display from the off-ramps; I think that storing these types of scripts all together separated perhaps by each map into its own directory would be useful.

**Comment by brucecrevensten** [comment]
Done, this is in the `mapventure-tools` repo.
